### ISSUE TITLE
Return the original libpostal components in the response

### ISSUE THREAD

**Issue by gosom** [gosom/address-parser-go-rest#3]
based on this discussion: https://github.com/gosom/address-parser-go-rest/issues/1

looks like it's a good idea to return the original libpostal components in the response. 

In particular:

in file `addressparser/addressparser.go` in the Address struct add an attributed:

````
Components []AddressComponent `json:"libpostal_components"`
```

AddressComponent should be a struct having 2 attributes (Label, Value) both strings. 

Components should contain the libpostal raw result .

**Comment by sberryman** [comment]
Good idea, leaves it to the dev to figure out what to do in edge cases.

**Comment by gosom** [comment]
Implement in v1.0.2 (https://github.com/gosom/address-parser-go-rest/releases/tag/v1.0.2)
